weights = {
    "gk": {
        ### Goalkeeping ###
        "Aerial Reach": "60",
        "Command Of Area": "40",
        "Communication": "30",
        "Eccentricity": "20",
        "First Touch": "30",
        "Handling": "50",
        "Kicking": "35",
        "One On Ones": "45",
        "Passing": "45",
        "Punching (Tendency)": "0",
        "Reflexes": "80",
        "Rushing Out (Tendency)": "40",
        "Throwing": "30",
        ### Technical ###
        "Free Kick Taking": "0",
        "Penalty Taking": "0",
        "Technique": "0",
        ### Mental ###
        "Aggression": "40",
        "Anticipation": "40",
        "Bravery": "30",
        "Composure": "40",
        "Concentration": "65",
        "Decisions": "50",
        "Determination": "20",
        "Flair": "10",
        "Leadership": "10",
        "Off The Ball": "0",
        "Positioning": "40",
        "Teamwork": "10",
        "Vision": "40",
        "Work Rate": "10",
        ### Physical ###
        "Acceleration": "70",
        "Agility": "100",
        "Balance": "20",
        "Jumping Reach": "45",
        "Natural Fitness": "10",
        "Pace": "50",
        "Stamina": "10",
        "Strength": "70",
    },
    "cd": {
        ### Technical ###
        "Corners": "5",
        "Crossing": "1",
        "Dribbling": "40",
        "Finishing": "10",
        "First Touch": "35",
        "Free Kick Taking": "10",
        "Heading": "55",
        "Long Shots": "10",
        "Long Throws": "5",
        "Marking": "55",
        "Passing": "55",
        "Penalty Taking": "10",
        "Tackling": "40",
        "Technique": "35",
        ### Mental ###
        "Aggression": "40",
        "Anticipation": "50",
        "Bravery": "30",
        "Composure": "80",
        "Concentration": "50",
        "Decisions": "50",
        "Determination": "20",
        "Flair": "10",
        "Leadership": "10",
        "Off The Ball": "10",
        "Positioning": "55",
        "Teamwork": "10",
        "Vision": "50",
        "Work Rate": "55",
        ### Physical ###
        "Acceleration": "90",
        "Agility": "60",
        "Balance": "35",
        "Jumping Reach": "65",
        "Natural Fitness": "10",
        "Pace": "90",
        "Stamina": "30",
        "Strength": "50",
    },
    "fb": {
        ### Technical ###
        "Corners": "30",
        "Crossing": "25",
        "Dribbling": "50",
        "Finishing": "10",
        "First Touch": "30",
        "Free Kick Taking": "10",
        "Heading": "20",
        "Long Shots": "10",
        "Long Throws": "30",
        "Marking": "45",
        "Passing": "45",
        "Penalty Taking": "10",
        "Tackling": "50",
        "Technique": "45",
        ### Mental ###
        "Aggression": "45",
        "Anticipation": "45",
        "Bravery": "20",
        "Composure": "30",
        "Concentration": "45",
        "Decisions": "45",
        "Determination": "20",
        "Flair": "20",
        "Leadership": "10",
        "Off The Ball": "70",
        "Positioning": "30",
        "Teamwork": "10",
        "Vision": "25",
        "Work Rate": "90",
        ### Physical ###
        "Acceleration": "100",
        "Agility": "60",
        "Balance": "25",
        "Jumping Reach": "40",
        "Natural Fitness": "10",
        "Pace": "90",
        "Stamina": "100",
        "Strength": "20",
    },
    "dm": {
        ### Technical ###
        "Corners": "10",
        "Crossing": "10",
        "Dribbling": "45",
        "Finishing": "20",
        "First Touch": "50",
        "Free Kick Taking": "30",
        "Heading": "10",
        "Long Shots": "40",
        "Long Throws": "5",
        "Marking": "20",
        "Passing": "65",
        "Penalty Taking": "10",
        "Tackling": "35",
        "Technique": "50",
        ### Mental ###
        "Aggression": "50",
        "Anticipation": "55",
        "Bravery": "30",
        "Composure": "60",
        "Concentration": "50",
        "Decisions": "65",
        "Determination": "20",
        "Flair": "50",
        "Leadership": "10",
        "Off The Ball": "40",
        "Positioning": "65",
        "Teamwork": "10",
        "Vision": "55",
        "Work Rate": "90",
        ### Physical ###
        "Acceleration": "65",
        "Agility": "45",
        "Balance": "35",
        "Jumping Reach": "15",
        "Natural Fitness": "10",
        "Pace": "70",
        "Stamina": "35",
        "Strength": "50",
    },
    "w": {
        ### Technical ###
        "Corners": "30",
        "Crossing": "65",
        "Dribbling": "55",
        "Finishing": "15",
        "First Touch": "30",
        "Free Kick Taking": "10",
        "Heading": "10",
        "Long Shots": "10",
        "Long Throws": "30",
        "Marking": "35",
        "Passing": "50",
        "Penalty Taking": "15",
        "Tackling": "35",
        "Technique": "50",
        ### Mental ###
        "Aggression": "35",
        "Anticipation": "45",
        "Bravery": "15",
        "Composure": "30",
        "Concentration": "35",
        "Decisions": "35",
        "Determination": "20",
        "Flair": "20",
        "Leadership": "10",
        "Off The Ball": "40",
        "Positioning": "35",
        "Teamwork": "10",
        "Vision": "35",
        "Work Rate": "75",
        ### Physical ###
        "Acceleration": "100",
        "Agility": "50",
        "Balance": "15",
        "Jumping Reach": "10",
        "Natural Fitness": "10",
        "Pace": "100",
        "Stamina": "30",
        "Strength": "20",
    },
    "am": {
        ### Technical ###
        "Corners": "5",
        "Crossing": "5",
        "Dribbling": "65",
        "Finishing": "65",
        "First Touch": "40",
        "Free Kick Taking": "30",
        "Heading": "10",
        "Long Shots": "20",
        "Long Throws": "1",
        "Marking": "5",
        "Passing": "50",
        "Penalty Taking": "15",
        "Tackling": "15",
        "Technique": "65",
        ### Mental ###
        "Aggression": "50",
        "Anticipation": "50",
        "Bravery": "20",
        "Composure": "35",
        "Concentration": "25",
        "Decisions": "40",
        "Determination": "20",
        "Flair": "20",
        "Leadership": "10",
        "Off The Ball": "35",
        "Positioning": "10",
        "Teamwork": "10",
        "Vision": "30",
        "Work Rate": "80",
        ### Physical ###
        "Acceleration": "100",
        "Agility": "30",
        "Balance": "50",
        "Jumping Reach": "10",
        "Natural Fitness": "10",
        "Pace": "80",
        "Stamina": "80",
        "Strength": "30",
    },
    "st": {
        ### Technical ###
        "Corners": "5",
        "Crossing": "5",
        "Dribbling": "75",
        "Finishing": "80",
        "First Touch": "50",
        "Free Kick Taking": "5",
        "Heading": "25",
        "Long Shots": "25",
        "Long Throws": "1",
        "Marking": "1",
        "Passing": "40",
        "Penalty Taking": "20",
        "Tackling": "5",
        "Technique": "65",
        ### Mental ###
        "Aggression": "50",
        "Anticipation": "50",
        "Bravery": "20",
        "Composure": "35",
        "Concentration": "5",
        "Decisions": "45",
        "Determination": "20",
        "Flair": "25",
        "Leadership": "10",
        "Off The Ball": "45",
        "Positioning": "5",
        "Teamwork": "10",
        "Vision": "20",
        "Work Rate": "60",
        ### Physical ###
        "Acceleration": "100",
        "Agility": "30",
        "Balance": "50",
        "Jumping Reach": "20",
        "Natural Fitness": "10",
        "Pace": "70",
        "Stamina": "65",
        "Strength": "25",
    },
}
