attributes = {
    "Acceleration": "",
    "Aggression": "",
    "Agility": "",
    "Anticipation": "",
    "Balance": "",
    "Bravery": "",
    "Composure": "",
    "Concentration": "",
    "Corners": "",
    "Crossing": "",
    "Decisions": "",
    "Determination": "",
    "Dribbling": "",
    "Finishing": "",
    "First Touch": "",
    "Flair": "",
    "Free Kick Taking": "",
    "Heading": "",
    "Jumping Reach": "",
    "Leadership": "",
    "Long Shots": "",
    "Long Throws": "",
    "Marking": "",
    "Natural Fitness": "",
    "Off The Ball": "",
    "Pace": "",
    "Passing": "",
    "Penalty Taking": "",
    "Positioning": "",
    "Stamina": "",
    "Strength": "",
    "Tackling": "",
    "Teamwork": "",
    "Technique": "",
    "Vision": "",
    "Work Rate": "",
}
